// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var aboutTemplate, afterLoginTemplate, beforeLoginTemplate, contactTemplate, dashboardTemplate, helpTemplate, leaderboardTemplate, loginNav, main, newEventTemplate, pastGames, playersByPercent, playersByUnit, privacyTemplate, profileTemplate, setActive, termsTemplate, unsetActive, upcomingGames;
    upcomingGames = [
      {
        homeTeam: "Brazil",
        awayTeam: "Argentina",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/BRA.png",
        awayFlag: "/assets/images/teams/ARG.png",
        date: "11 June 20:00",
        overUnder: "2.5",
        homeHandicap: "-1.5",
        awayHandicap: "+1.5",
        hadPieChart: "/assets/images/piecharts/three1.png",
        overUnderPieChart: "/assets/images/piecharts/two1.png",
        handicapPieChart: "/assets/images/piecharts/two2.png"
      }, {
        homeTeam: "Switzerland",
        awayTeam: "France",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/SWZ.png",
        awayFlag: "/assets/images/teams/FRA.png",
        date: "12 June 20:00",
        overUnder: "2.5",
        homeHandicap: "+1.5",
        awayHandicap: "-1.5",
        hadPieChart: "/assets/images/piecharts/three2.png",
        overUnderPieChart: "/assets/images/piecharts/two3.png",
        handicapPieChart: "/assets/images/piecharts/two4.png"
      }, {
        homeTeam: "Germany",
        awayTeam: "Spain",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/GER.png",
        awayFlag: "/assets/images/teams/SPA.png",
        date: "13 June 20:00",
        overUnder: "2.5",
        homeHandicap: "-1.5",
        awayHandicap: "+1.5",
        hadPieChart: "/assets/images/piecharts/three3.png",
        overUnderPieChart: "/assets/images/piecharts/two5.png",
        handicapPieChart: "/assets/images/piecharts/two2.png"
      }, {
        homeTeam: "United States",
        awayTeam: "Ghana",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/USA.png",
        awayFlag: "/assets/images/teams/GHA.png",
        date: "28 June 20:00",
        overUnder: "4.5",
        homeHandicap: "-2.5",
        awayHandicap: "+2.5",
        hadPieChart: "/assets/images/piecharts/three4.png",
        overUnderPieChart: "/assets/images/piecharts/two1.png",
        handicapPieChart: "/assets/images/piecharts/two4.png"
      }, {
        homeTeam: "Belgium",
        awayTeam: "Chile",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/BEL.png",
        awayFlag: "/assets/images/teams/CHI.png",
        date: "29 June 20:00",
        overUnder: "4.5",
        homeHandicap: "-2.5",
        awayHandicap: "+2.5",
        hadPieChart: "/assets/images/piecharts/three4.png",
        overUnderPieChart: "/assets/images/piecharts/two1.png",
        handicapPieChart: "/assets/images/piecharts/two4.png"
      }, {
        homeTeam: "Italy",
        awayTeam: "Japan",
        homeScore: "",
        awayScore: "",
        homeFlag: "/assets/images/teams/ITA.png",
        awayFlag: "/assets/images/teams/JPN.png",
        date: "30 June 20:00",
        overUnder: "4.5",
        homeHandicap: "-2.5",
        awayHandicap: "+2.5",
        hadPieChart: "/assets/images/piecharts/three4.png",
        overUnderPieChart: "/assets/images/piecharts/two1.png",
        handicapPieChart: "/assets/images/piecharts/two4.png"
      }
    ];
    pastGames = [
      {
        homeTeam: "South Korea",
        awayTeam: "Australia",
        homeScore: "1",
        awayScore: "2",
        homeFlag: "/assets/images/teams/KOR.png",
        awayFlag: "/assets/images/teams/AUS.png",
        date: "6 June 20:00",
        overUnder: "2.5",
        homeHandicap: "-1.5",
        awayHandicap: "+1.5",
        hadPieChart: "/assets/images/piecharts/three1.png",
        overUnderPieChart: "/assets/images/piecharts/two5.png",
        handicapPieChart: "/assets/images/piecharts/two2.png"
      }, {
        homeTeam: "Uruguay",
        awayTeam: "Russia",
        homeScore: "3",
        awayScore: "1",
        homeFlag: "/assets/images/teams/URU.png",
        awayFlag: "/assets/images/teams/RUS.png",
        date: "6 June 20:00",
        overUnder: "2.5",
        homeHandicap: "-1.5",
        awayHandicap: "+1.5",
        hadPieChart: "/assets/images/piecharts/three1.png",
        overUnderPieChart: "/assets/images/piecharts/two5.png",
        handicapPieChart: "/assets/images/piecharts/two2.png"
      }, {
        homeTeam: "Portugal",
        awayTeam: "Nigeria",
        homeScore: "1",
        awayScore: "2",
        homeFlag: "/assets/images/teams/POR.png",
        awayFlag: "/assets/images/teams/NGA.png",
        date: "6 June 20:00",
        overUnder: "2.5",
        homeHandicap: "-1.5",
        awayHandicap: "+1.5",
        hadPieChart: "/assets/images/piecharts/three1.png",
        overUnderPieChart: "/assets/images/piecharts/two5.png",
        handicapPieChart: "/assets/images/piecharts/two2.png"
      }
    ];
    playersByPercent = [
      {
        rank: "1",
        name: "Bob",
        percent: "78%",
        units: "1549",
        followers: "123",
        avatar: "/assets/images/profiles/1.jpg"
      }, {
        rank: "2",
        name: "Joe",
        percent: "77%",
        units: "1651",
        followers: "138",
        avatar: "/assets/images/profiles/2.jpg"
      }, {
        rank: "3",
        name: "Bill",
        percent: "75%",
        units: "1409",
        followers: "121",
        avatar: "/assets/images/profiles/3.jpg"
      }, {
        rank: "4",
        name: "Ron",
        percent: "74%",
        units: "1210",
        followers: "90",
        avatar: "/assets/images/profiles/4.jpg"
      }, {
        rank: "5",
        name: "Jim",
        percent: "61%",
        units: "1319",
        followers: "202",
        avatar: "/assets/images/profiles/5.jpg"
      }, {
        rank: "6",
        name: "Ray",
        percent: "59%",
        units: "1200",
        followers: "121",
        avatar: "/assets/images/profiles/6.jpg"
      }, {
        rank: "7",
        name: "Lina",
        percent: "59%",
        units: "1199",
        followers: "89",
        avatar: "/assets/images/profiles/7.jpg"
      }, {
        rank: "8",
        name: "Rick",
        percent: "58%",
        units: "1105",
        followers: "70",
        avatar: "/assets/images/profiles/8.jpg"
      }, {
        rank: "9",
        name: "Tina",
        percent: "57%",
        units: "1201",
        followers: "20",
        avatar: "/assets/images/profiles/9.jpg"
      }, {
        rank: "10",
        name: "Ank",
        percent: "55%",
        units: "905",
        followers: "37",
        avatar: "/assets/images/profiles/10.jpg"
      }
    ];
    playersByUnit = [
      {
        rank: "1",
        name: "Joe",
        percent: "77%",
        units: "1651",
        followers: "138",
        avatar: "/assets/images/profiles/2.jpg"
      }, {
        rank: "2",
        name: "Bob",
        percent: "78%",
        units: "1549",
        followers: "123",
        avatar: "/assets/images/profiles/1.jpg"
      }, {
        rank: "3",
        name: "Bill",
        percent: "75%",
        units: "1409",
        followers: "121",
        avatar: "/assets/images/profiles/3.jpg"
      }, {
        rank: "4",
        name: "Jim",
        percent: "61%",
        units: "1319",
        followers: "202",
        avatar: "/assets/images/profiles/5.jpg"
      }, {
        rank: "5",
        name: "Ron",
        percent: "74%",
        units: "1210",
        followers: "90",
        avatar: "/assets/images/profiles/4.jpg"
      }, {
        rank: "6",
        name: "Ray",
        percent: "59%",
        units: "1200",
        followers: "121",
        avatar: "/assets/images/profiles/6.jpg"
      }, {
        rank: "7",
        name: "Lina",
        percent: "59%",
        units: "1199",
        followers: "89",
        avatar: "/assets/images/profiles/7.jpg"
      }, {
        rank: "8",
        name: "Tina",
        percent: "57%",
        units: "1201",
        followers: "20",
        avatar: "/assets/images/profiles/9.jpg"
      }, {
        rank: "9",
        name: "Rick",
        percent: "58%",
        units: "1105",
        followers: "70",
        avatar: "/assets/images/profiles/8.jpg"
      }, {
        rank: "10",
        name: "Ank",
        percent: "55%",
        units: "905",
        followers: "37",
        avatar: "/assets/images/profiles/10.jpg"
      }
    ];
    unsetActive = function() {
      $('#header-navlinks').children().removeClass('active');
      return $('#login-nav').children().children().removeClass('active');
    };
    setActive = function(lnk) {
      lnk = $(lnk);
      unsetActive();
      return lnk.parent().addClass('active');
    };
    dashboardTemplate = Handlebars.compile($("#dashboard-template").html());
    leaderboardTemplate = Handlebars.compile($("#leaderboard-template").html());
    helpTemplate = Handlebars.compile($("#help-template").html());
    aboutTemplate = Handlebars.compile($("#about-template").html());
    contactTemplate = Handlebars.compile($("#contact-template").html());
    termsTemplate = Handlebars.compile($("#terms-template").html());
    privacyTemplate = Handlebars.compile($("#privacy-template").html());
    beforeLoginTemplate = Handlebars.compile($("#before-login-template").html());
    afterLoginTemplate = Handlebars.compile($("#after-login-template").html());
    profileTemplate = Handlebars.compile($("#profile-template").html());
    newEventTemplate = Handlebars.compile($("#new-event-template").html());
    loginNav = $('#login-nav');
    loginNav.html(beforeLoginTemplate);
    main = $('#main');
    main.html(dashboardTemplate({
      pageTitle: "Upcoming games:",
      games: upcomingGames,
      playersByPercent: playersByPercent,
      playersByUnit: playersByUnit
    }));
    $('#header-navlinks').on('click', '#upcoming-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(dashboardTemplate({
        pageTitle: "Upcoming games:",
        games: upcomingGames,
        playersByPercent: playersByPercent,
        playersByUnit: playersByUnit
      }));
    });
    $('#header-navlinks').on('click', '#results-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(dashboardTemplate({
        pageTitle: "Past games:",
        games: pastGames,
        playersByPercent: playersByPercent,
        playersByUnit: playersByUnit
      }));
    });
    $('#header-navlinks').on('click', '#leaderboard-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(leaderboardTemplate({
        playersByPercent: playersByPercent,
        playersByUnit: playersByUnit
      }));
    });
    $('#footer-navlinks').on('click', '#help-link', function(e) {
      e.preventDefault();
      main.html(helpTemplate());
      return unsetActive();
    });
    $('#footer-navlinks').on('click', '#about-link', function(e) {
      e.preventDefault();
      main.html(aboutTemplate());
      return unsetActive();
    });
    $('#footer-navlinks').on('click', '#contact-link', function(e) {
      e.preventDefault();
      main.html(contactTemplate());
      return unsetActive();
    });
    $('#footer-navlinks').on('click', '#terms-link', function(e) {
      e.preventDefault();
      main.html(termsTemplate());
      return unsetActive();
    });
    $('#footer-navlinks').on('click', '#privacy-link', function(e) {
      e.preventDefault();
      main.html(privacyTemplate());
      return unsetActive();
    });
    $('#login-nav').on('click', 'button', function(e) {
      e.preventDefault();
      return loginNav.html(afterLoginTemplate());
    });
    $('#login-nav').on('click', '#before-login-link', function(e) {
      e.preventDefault();
      loginNav.html(beforeLoginTemplate());
      return main.html(upcomingTemplate());
    });
    $('#login-nav').on('click', '#profile-link', function(e) {
      e.preventDefault();
      main.html(profileTemplate());
      return setActive(this);
    });
    $('#login-nav').on('click', '#new-event-link', function(e) {
      e.preventDefault();
      main.html(newEventTemplate());
      return setActive(this);
    });
    $('#paid-event').on('click', function(e) {
      return $('#event-price-show').removeClass('hide');
    });
    return $('#free-event').on('click', function(e) {
      return $('#event-price-show').addClass('hide');
    });
  });

}).call(this);

//# sourceMappingURL=main.map
